### ISSUE TITLE
npm run generate is broken

### ISSUE THREAD

**Issue by hansiemithun** [jonidelv/generator-create-redux-app#11]
Getting below error when I try to run generate. 

```
MITHHA-M-J0JL:yo-react-redux-app mithha$ yarn generate
yarn run v1.7.0
warning package.json: No license field
$ plop --plopfile generators/index.js
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/mithha/Documents/personal/yo-react-redux-app/src/modules'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.<anonymous> (/Users/mithha/Documents/personal/yo-react-redux-app/generators/utils/componentExists.js:6:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mithha/Documents/personal/yo-react-redux-app/generators/component/index.js:1:87)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
MITHHA-M-J0JL:yo-react-redux-app mithha$


```

Whats the cause for this? Please assist if i am missing something in the installations

**Comment by jonidelv** [comment]
I just pushed a new version. Please update the generator -> `npm install -g generator-create-redux-app` and try again. Should be wroking fine.

**Comment by hansiemithun** [comment]
Super thanks @jonidelv. I am closing this but I have one more query, which i will raise it as a separate ticket regarding sass support
